version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: keycloak-pg
    networks:
      - keycloak-network
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - ./keycloak-pgdata/:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    container_name: keycloak-app
    networks:
      - keycloak-network
    ports:
      - '8087:8080'
    env_file:
      - .env
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - db
networks:
  keycloak-network:
