#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE role $KEYCLOAK_DB_USER login password '$KEYCLOAK_DB_PASSWORD';
  CREATE DATABASE $KEYCLOAK_DB ENCODING 'UTF-8' LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8' TEMPLATE template0 OWNER $KEYCLOAK_DB_USER;
EOSQL
